services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nats
      - redis
      - mongo
      - rabbitmq
  nats:
    image: nats:2-alpine
    ports:
      - 4222:4222
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
  dozzle:
    image: amir20/dozzle:latest
    environment:
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_FILTER: "label=yifan"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
