version: "3"

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nats
      - redis
      - rabbitmq
  nats:
    image: nats:2-alpine
    ports:
      - 4222:4222
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
