---
name: "Continuous Delivery"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 🐳 apps:create
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: apps:exists
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          apps:exists ${{ github.event.repository.name }}
    - name: apps:create
      if: ${{ failure() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          apps:create ${{ github.event.repository.name }}
