---
name: "Continuous Delivery"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  create:
    name: 🐳 Provision
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: apps:exists
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          apps:exists ${{ github.event.repository.name }}
    - name: apps:create
      if: ${{ failure() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          apps:create ${{ github.event.repository.name }}
  config:
    name: ⚙️ Configuration
    needs: create
    runs-on: ubuntu-latest
    steps:
    - name: docker-option:add
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker-options:add ${{ github.event.repository.name }} deploy "-v /var/run/docker.sock:/var/run/docker.sock"
    - name: config:set
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          config:set --no-restart ${{ github.event.repository.name }} NATS_URL=${{ secrets.NATS_SERVICE }}
    - name: config:set
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          config:set --no-restart ${{ github.event.repository.name }} RABBITMQ_URL=${{ secrets.AMQP_SERVICE }}
  deploy:
    name: 🚀 Deploy
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: git:checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git:deploy
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}/${{ github.event.repository.name }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
